name: Terraform Deployment - Azure
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      # Fetch dynamic SP credentials from Vault
      - name: Fetch Azure Credentials from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://20.82.210.227:8200
          role: gh-actions-role
          method: jwt
          secrets: |
            azure/creds/terraform-role client_id     | ARM_CLIENT_ID ;
            azure/creds/terraform-role client_secret | ARM_CLIENT_SECRET

      # Subscription & Tenant are static — store in GitHub Secrets
      - name: Set Static Azure Env Vars
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
